use_frameworks!

platform :ios, '11.0'

target 'IosAwnFcmCore_Example' do
  #pod 'IosAwnCore', :path => '../../IosAwnCore/'
  pod 'IosAwnFcmCore', :path => '../'

  target 'IosAwnFcmCore_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
