use_frameworks!

platform :ios, '11.0'

target 'IosAwnFcmCore_Example' do
  pod 'IosAwnCore', '~> 0.7.7'#:path => '../../IosAwnCore/'#
  pod 'IosAwnFcmCore', :path => '../'

  target 'IosAwnFcmCore_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
