use_frameworks!

platform :ios, '10.0'

target 'IosAwnFcmCore_Example' do
  pod 'IosAwnFcmCore', :path => '../'

  target 'IosAwnFcmCore_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
